# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, workflow_dispatch]

jobs:
  job1:
    name: First Job name
    runs-on: ubuntu-latest # Specify the compute resource the job will run on
    steps:
    - name: Step 1
      uses: actions/checkout@v2
    - name: Step 2
      run: env | sort
  job2:
    name: Second Job name
    runs-on: windows-latest # Specify the compute resource the job will run on
    steps:
    - name: Step 1
      uses: actions/checkout@v2
    - name: Step 2
      run: "Get-ChildItem Env: | Sort-Object Name"
  job3:
    name: Third Job dependent
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
    - name: Step 1
      uses: actions/checkout@v2
    - name: Step 2
      run: echo "Job 3 done!"